[tool.poetry]
name = "buzzbird"
version = "0.1.0"
description = "ğŸŒŸ Sync tweets â¡ï¸ weibo, in an easy way."
authors = ["Aris Chow <arischow@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
django = "^2.2"
djangorestframework = "^3.11.0"
django-q = "^1.0.2"
requests-toolbelt = "^0.9.1"
pillow = "^7.0.0"
psycopg2-binary = "^2.8.4"
rollbar = "^0.14.7"
python-dateutil = "^2.8.1"
instaloader = "^4.5.3"
ipython = "^7.11.1"
python-twitter = "^3.5"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pytest-django = "^3.8.0"
mimesis = "^3.3.0"
python-dotenv = "^0.10.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
