[tool.poetry]
name = "buzzbird"
version = "0.2.0"
description = "ğŸŒŸ Sync tweets â¡ï¸ weibo, in an easy way."
authors = ["Aris Chow <arischow@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "~3.8"
requests = "^2.22.0"
django = "^2.2"
djangorestframework = "^3.11.0"
django-q = "^1.0.2"
requests-toolbelt = "^0.9.1"
pillow = "^7.2.0"
psycopg2-binary = "==2.8.4"
rollbar = "^0.16.2"
python-dateutil = "^2.8.1"
instaloader = "^4.9.5"
ipython = "^8.10.0"
python-twitter = "^3.5"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pytest-django = "^3.8.0"
mimesis = "^3.3.0"
python-dotenv = "^0.10.3"

[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"
src_paths = ["gomashio"]
